#!/bin/bash
#ddev-generated

# =============================================================================
# OpenCode DDEV Entrypoint
# =============================================================================

# --- 0. Ensure HOME directory is writable ---
if [ -d "$HOME" ] && [ ! -w "$HOME" ]; then
  sudo chown -R "$(id -u):$(id -g)" "$HOME"
fi

# --- 1. Copy CLAUDE.md and config from agents-sync volume ---
AGENTS_DATA="/agents-data"
if [ -d "$AGENTS_DATA" ]; then
  OC_CONFIG="$HOME/.config/opencode"
  mkdir -p "$OC_CONFIG"
  [ -f "$AGENTS_DATA/CLAUDE.md" ] && cp "$AGENTS_DATA/CLAUDE.md" "$OC_CONFIG/CLAUDE.md"
  for f in "$AGENTS_DATA"/*.json; do
    [ -f "$f" ] && cp "$f" "$OC_CONFIG/$(basename "$f")"
  done
fi

# --- 2. Set up SSH (keys generated by ddev-ai-ssh add-on) ---
SSH_KEY_DIR="/var/www/html/.ddev/.agent-ssh-keys"
mkdir -p ~/.ssh && chmod 700 ~/.ssh

# SSH client: copy private key for connecting to web/beads
cp "$SSH_KEY_DIR/id_ed25519" ~/.ssh/ddev_agent_key 2>/dev/null
chmod 600 ~/.ssh/ddev_agent_key 2>/dev/null

# Detect web container username (DDEV maps host user, name varies)
WEB_USER=$(stat -c '%U' /var/www/html/.ddev/.agent-ssh-keys/id_ed25519 2>/dev/null || echo "ddev")
if ! sed -n '/^Host web$/,/^Host /p' ~/.ssh/config 2>/dev/null | grep -q "^    User "; then
  sed -i "/^Host web$/a\\    User $WEB_USER" ~/.ssh/config 2>/dev/null
fi

# SSH server: authorized_keys for Ralph to connect to this container
cp "$SSH_KEY_DIR/id_ed25519.pub" ~/.ssh/authorized_keys 2>/dev/null
chmod 600 ~/.ssh/authorized_keys 2>/dev/null

# Start sshd for Ralph access
env | grep -E '^(DDEV_|IS_DDEV_PROJECT|HOME=|PATH=|LANG|TZ=|PLAYWRIGHT_)' \
    | sed 's/^/export /' | sudo tee /etc/ddev-env > /dev/null
sudo chmod 644 /etc/ddev-env
sudo /usr/sbin/sshd 2>/dev/null || true

# --- 3. Install notifier plugin if not already installed ---
if [ ! -d "$HOME/.config/opencode/node_modules/@mohak34/opencode-notifier" ]; then
  mkdir -p "$HOME/.config/opencode"
  cd "$HOME/.config/opencode"
  npm install --save @mohak34/opencode-notifier@latest 2>/dev/null || true
  cd /var/www/html
fi

exec "$@"
