#!/bin/bash
#ddev-generated

# =============================================================================
# OpenCode DDEV Entrypoint
# =============================================================================

# --- 0. Ensure HOME directory is writable ---
if [ -d "$HOME" ] && [ ! -w "$HOME" ]; then
  sudo chown -R "$(id -u):$(id -g)" "$HOME"
fi

# --- 1. Copy CLAUDE.md and config from agents-sync volume ---
AGENTS_DATA="/agents-data"
if [ -d "$AGENTS_DATA" ]; then
  OC_CONFIG="$HOME/.config/opencode"
  mkdir -p "$OC_CONFIG"
  [ -f "$AGENTS_DATA/CLAUDE.md" ] && cp "$AGENTS_DATA/CLAUDE.md" "$OC_CONFIG/CLAUDE.md"
  for f in "$AGENTS_DATA"/*.json; do
    [ -f "$f" ] && cp "$f" "$OC_CONFIG/$(basename "$f")"
  done
fi

# --- 2. Set up SSH (keys generated by ddev-ai-ssh add-on) ---
SSH_KEY_DIR="/var/www/html/.ddev/.agent-ssh-keys"
mkdir -p ~/.ssh && chmod 700 ~/.ssh

# SSH client: copy private key for connecting to web/beads
cp "$SSH_KEY_DIR/id_ed25519" ~/.ssh/ddev_agent_key 2>/dev/null
chmod 600 ~/.ssh/ddev_agent_key 2>/dev/null

# Detect web container username (written by ai-ssh-setup.sh in the web container)
# Wait for the web container to write its username (max 15s)
for i in $(seq 1 15); do
  [ -f /var/www/html/.ddev/.agent-ssh-keys/web-user ] && break
  sleep 1
done
WEB_USER=$(cat /var/www/html/.ddev/.agent-ssh-keys/web-user 2>/dev/null || echo "ddev")
if ! sed -n '/^Host web$/,/^Host /p' ~/.ssh/config 2>/dev/null | grep -q "^    User "; then
  sed -i "/^Host web$/a\\    User $WEB_USER" ~/.ssh/config 2>/dev/null
fi

# SSH server: authorized_keys for Ralph to connect to this container
cp "$SSH_KEY_DIR/id_ed25519.pub" ~/.ssh/authorized_keys 2>/dev/null
chmod 600 ~/.ssh/authorized_keys 2>/dev/null

# Start sshd for Ralph access
env | grep -E '^(DDEV_|IS_DDEV_PROJECT|HOME=|PATH=|LANG|TZ=|PLAYWRIGHT_)' \
    | sed 's/^/export /' | sudo tee /etc/ddev-env > /dev/null
sudo chmod 644 /etc/ddev-env
sudo /usr/sbin/sshd 2>/dev/null || true

# --- 3. Install notifier plugin if not already installed ---
if [ ! -d "$HOME/.config/opencode/node_modules/@mohak34/opencode-notifier" ]; then
  mkdir -p "$HOME/.config/opencode"
  cd "$HOME/.config/opencode"
  npm install --save @mohak34/opencode-notifier@latest 2>/dev/null || true
  cd /var/www/html
fi

# --- 4. Multica daemon (optional) ---
# Activated only if /home/opencode/.env.multica has a non-empty MULTICA_TOKEN.
# The env file is mounted from the shared ~/.ddev/multica/ directory on the
# host, so one configuration enables the daemon in every Multica-aware addon.
# Watch list is managed automatically (`multica login` subscribes the daemon
# to all UI workspaces) — the user controls it from the Multica panel.
MULTICA_ENV_FILE="$HOME/.env.multica"
if [ -s "$MULTICA_ENV_FILE" ] && command -v multica >/dev/null 2>&1; then
  set -a
  # shellcheck disable=SC1090
  . "$MULTICA_ENV_FILE"
  set +a

  if [ -z "${MULTICA_TOKEN:-}" ]; then
    echo "[multica] $MULTICA_ENV_FILE has no MULTICA_TOKEN — daemon disabled."
  elif [ -z "${MULTICA_SERVER_URL:-}" ] || [ -z "${MULTICA_APP_URL:-}" ]; then
    echo "[multica] MULTICA_SERVER_URL or MULTICA_APP_URL missing — daemon disabled."
  else
    # Identity for this runtime in the Multica UI (always tied to the DDEV
    # project name so the user can tell runtimes apart at a glance).
    export MULTICA_DAEMON_DEVICE_NAME="ddev-${DDEV_SITENAME}-opencode"
    export MULTICA_AGENT_RUNTIME_NAME="OpenCode DDEV (${DDEV_SITENAME})"

    echo "[multica] starting daemon as '$MULTICA_AGENT_RUNTIME_NAME'..."
    multica config set server_url "$MULTICA_SERVER_URL" >/dev/null 2>&1 || true
    multica config set app_url    "$MULTICA_APP_URL"    >/dev/null 2>&1 || true

    # Non-interactive login. `--token=` (empty) reads from stdin so the
    # token never lands in shell history; fall back to flag form if the
    # CLI version doesn't support the stdin shortcut.
    printf '%s\n' "$MULTICA_TOKEN" | multica login --token= >/dev/null 2>&1 || \
      multica login --token="$MULTICA_TOKEN" >/dev/null 2>&1 || \
      echo "[multica] login failed — check token validity."

    multica daemon stop >/dev/null 2>&1 || true
    if multica daemon start >/dev/null 2>&1; then
      echo "[multica] daemon running (logs: $HOME/.multica/daemon.log)"
    else
      echo "[multica] WARNING: daemon failed to start — see $HOME/.multica/daemon.log"
    fi
  fi
elif [ ! -s "$MULTICA_ENV_FILE" ]; then
  echo "[multica] disabled (no $MULTICA_ENV_FILE or file is empty)."
fi

exec "$@"
